2024-10-29 17:37:43,131 - INFO - Server started, log file: ./logs/2024-10-29_17-37-43.log
2024-10-29 17:37:43,136 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8000
 * Running on http://192.168.1.111:8000
2024-10-29 17:37:43,137 - INFO - [33mPress CTRL+C to quit[0m
2024-10-29 17:37:45,243 - INFO - Login page accessed
2024-10-29 17:37:45,247 - INFO - 192.168.1.111 - - [29/Oct/2024 17:37:45] "GET / HTTP/1.1" 200 -
2024-10-29 17:37:45,303 - INFO - 192.168.1.111 - - [29/Oct/2024 17:37:45] "GET /static/LoginPage.css HTTP/1.1" 200 -
2024-10-29 17:37:48,348 - INFO - View page accessed
2024-10-29 17:37:48,350 - INFO - 192.168.1.111 - - [29/Oct/2024 17:37:48] "POST /view HTTP/1.1" 200 -
2024-10-29 17:37:48,398 - ERROR - Exception on /static/stylesheet.css [GET]
Traceback (most recent call last):
  File "/home/weidi/Desktop/4BI/ITP√ú/Heatseekers/PyCharm/.venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/weidi/Desktop/4BI/ITP√ú/Heatseekers/PyCharm/.venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/weidi/Desktop/4BI/ITP√ú/Heatseekers/PyCharm/.venv/lib/python3.12/site-packages/flask/app.py", line 270, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/weidi/Desktop/4BI/ITP√ú/Heatseekers/PyCharm/.venv/lib/python3.12/site-packages/flask/app.py", line 318, in send_static_file
    return send_from_directory(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/weidi/Desktop/4BI/ITP√ú/Heatseekers/PyCharm/.venv/lib/python3.12/site-packages/flask/helpers.py", line 552, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/weidi/Desktop/4BI/ITP√ú/Heatseekers/PyCharm/.venv/lib/python3.12/site-packages/werkzeug/utils.py", line 575, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/weidi/Desktop/4BI/ITP√ú/Heatseekers/PyCharm/.venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/weidi/Desktop/4BI/ITP√ú/Heatseekers/PyCharm/.venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/weidi/Desktop/4BI/ITP√ú/Heatseekers/PyCharm/.venv/lib/python3.12/site-packages/flask/app.py", line 765, in handle_user_exception
    return self.handle_http_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/weidi/Desktop/4BI/ITP√ú/Heatseekers/PyCharm/.venv/lib/python3.12/site-packages/flask/app.py", line 740, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: errorhandler() takes 0 positional arguments but 1 was given
2024-10-29 17:37:48,399 - INFO - Video feed accessed
2024-10-29 17:37:48,401 - INFO - 192.168.1.111 - - [29/Oct/2024 17:37:48] "GET /static/x.js HTTP/1.1" 200 -
2024-10-29 17:37:48,403 - INFO - 192.168.1.111 - - [29/Oct/2024 17:37:48] "[35m[1mGET /static/stylesheet.css HTTP/1.1[0m" 500 -
2024-10-29 17:37:48,418 - ERROR - Error on request:
Traceback (most recent call last):
  File "/home/weidi/Desktop/4BI/ITP√ú/Heatseekers/PyCharm/.venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/weidi/Desktop/4BI/ITP√ú/Heatseekers/PyCharm/.venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/weidi/Desktop/4BI/ITP√ú/Heatseekers/PyCharm/.venv/lib/python3.12/site-packages/flask/app.py", line 270, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/weidi/Desktop/4BI/ITP√ú/Heatseekers/PyCharm/.venv/lib/python3.12/site-packages/flask/app.py", line 318, in send_static_file
    return send_from_directory(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/weidi/Desktop/4BI/ITP√ú/Heatseekers/PyCharm/.venv/lib/python3.12/site-packages/flask/helpers.py", line 552, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/weidi/Desktop/4BI/ITP√ú/Heatseekers/PyCharm/.venv/lib/python3.12/site-packages/werkzeug/utils.py", line 575, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/weidi/Desktop/4BI/ITP√ú/Heatseekers/PyCharm/.venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/weidi/Desktop/4BI/ITP√ú/Heatseekers/PyCharm/.venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/weidi/Desktop/4BI/ITP√ú/Heatseekers/PyCharm/.venv/lib/python3.12/site-packages/flask/app.py", line 765, in handle_user_exception
    return self.handle_http_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/weidi/Desktop/4BI/ITP√ú/Heatseekers/PyCharm/.venv/lib/python3.12/site-packages/flask/app.py", line 740, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: errorhandler() takes 0 positional arguments but 1 was given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/weidi/Desktop/4BI/ITP√ú/Heatseekers/PyCharm/.venv/lib/python3.12/site-packages/werkzeug/serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "/home/weidi/Desktop/4BI/ITP√ú/Heatseekers/PyCharm/.venv/lib/python3.12/site-packages/werkzeug/serving.py", line 331, in execute
    application_iter = app(environ, start_response)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/weidi/Desktop/4BI/ITP√ú/Heatseekers/PyCharm/.venv/lib/python3.12/site-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/weidi/Desktop/4BI/ITP√ú/Heatseekers/PyCharm/.venv/lib/python3.12/site-packages/flask/app.py", line 1476, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/weidi/Desktop/4BI/ITP√ú/Heatseekers/PyCharm/.venv/lib/python3.12/site-packages/flask/app.py", line 823, in handle_exception
    server_error = self.ensure_sync(handler)(server_error)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: errorhandler() takes 0 positional arguments but 1 was given
2024-10-29 17:37:48,762 - INFO - 192.168.1.111 - - [29/Oct/2024 17:37:48] "GET /video_feed HTTP/1.1" 200 -
