2024-10-21 12:58:11,908 - INFO - Server started, log file: ./logs/2024-10-21_12-58-11.log
2024-10-21 12:58:11,912 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8000
 * Running on http://10.21.16.72:8000
2024-10-21 12:58:11,912 - INFO - [33mPress CTRL+C to quit[0m
2024-10-21 12:58:14,180 - INFO - Login page accessed
2024-10-21 12:58:14,183 - INFO - 10.21.16.72 - - [21/Oct/2024 12:58:14] "GET / HTTP/1.1" 200 -
2024-10-21 12:58:14,917 - INFO - 10.21.16.72 - - [21/Oct/2024 12:58:14] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2024-10-21 12:58:18,537 - ERROR - Exception on /view [POST]
Traceback (most recent call last):
  File "/home/weidi/Desktop/4BI/ITPÃœ/Heatseekers/PyCharm/.venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/weidi/Desktop/4BI/ITPÃœ/Heatseekers/PyCharm/.venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/weidi/Desktop/4BI/ITPÃœ/Heatseekers/PyCharm/.venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/weidi/Desktop/4BI/ITPÃœ/Heatseekers/PyCharm/.venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/weidi/Desktop/4BI/ITPÃœ/Heatseekers/PyCharm/server.py", line 37, in view
    user = get_User("data/user.json")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/weidi/Desktop/4BI/ITPÃœ/Heatseekers/PyCharm/functions.py", line 51, in get_User
    data = json.load(file)
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-10-21 12:58:18,540 - INFO - 10.21.16.72 - - [21/Oct/2024 12:58:18] "[35m[1mPOST /view HTTP/1.1[0m" 500 -
